# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Framework Bootstrapper CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install required dependencies
      run: |
        python -m pip install --upgrade pip
        pip install clint pytest PyInquirer pyfiglet
    - name: Test Framework Boostrapper CLI
      shell: python
      run: |
        import os
        def validate():
          works = os.system("cd framework_jumpstarter && python3 entry.py")
          if works:
            return True
          else:
            return False
        validate()
